### PR TITLE
Screenshots for rackerlabs/encore-ui#1142

### PR DESCRIPTION
**Pull request by comeatmebro**
See rackerlabs/encore-ui#1142

### CODE REVIEW

**Comment by CITguy** [comment]
LGTM

**Comment by CITguy** [comment]
@glynnis, are you good with the screenshots? It seems the new rxForm margins are in effect in the new images.

**Comment by glynnis** [comment]
@CITguy I'm concerned that the "Unsaved changes" lines (page subtitles) are getting pushed down, as that shouldn't be the case. Does that mean page subtitles across the board are pushed down (because we use them heavily in Encore)? Or is that just an error in this particular case because there's a form?

**Comment by CITguy** [comment]
@glynnis, the "Unsaved changes" line is getting pushed down because the `span.title` that wraps the content is coded to be within the rxForm (below the top margin).  Should this block rackerlabs/encore-ui#1142?

**Comment by CITguy** [comment]
If it were outside of the form, it would look like so.

screen shot 2015-09-14 at 2 50 05 pm

**Comment by CITguy** [comment]
However, that cannot be done because the "Save Now" button needs to be within the form... hmm.

**Comment by CITguy** [comment]
This is something that will require a fix to the markup. I wouldn't want to block `rx-tags` because of this.

**Pull request merged**
