### PR TITLE
Screenshots for rackerlabs/encore-ui#1701

### PR DESCRIPTION
**Pull request by comeatmebro**
See rackerlabs/encore-ui#1701.

### CODE REVIEW

**Comment by Droogans** [comment]
@CITguy I think this is how the newer version of FF is rendering the page.

I say we merge this.

**Comment by CITguy** [comment]
I'm trying with Firefox 42, we'll see what (if anything) changes. Keep this open for now.

**Comment by CITguy** [comment]
I've gotta close this. Logic for submitting PRs against this repo have it limited to one per framework PR.

**Comment by CITguy** [comment]
reopening temporarily to trigger error on codeship

**Pull request closed without merging**
