### PR TITLE
Screenshots for rackerlabs/encore-ui#1093

### PR DESCRIPTION
**Pull request by comeatmebro**
See rackerlabs/encore-ui#1093

### CODE REVIEW

**Comment by Droogans** [comment]
@glynnis I messed up the visual regression builds and now we're a little behind. This has both rxSpinner images as well as some backed up visual changes from last week.

Can you check out the changes to the demo layout and make sure everything still looks alright?

**Comment by Droogans** [comment]
@parlarjb @CITguy @TheNando these screenshots look alright to you?

**Comment by TheNando** [comment]
Is there no margin around the spinner?

**Comment by Droogans** [comment]
Nope. That's what it looks like.

**Pull request merged**
