### PR TITLE
Screenshots for rackerlabs/encore-ui#1695

### PR DESCRIPTION
**Pull request by comeatmebro**
See rackerlabs/encore-ui#1695.

### CODE REVIEW

**Comment by Droogans** [comment]
@CITguy this is the second time today that this screenshot has shown up in that pull request.

It looks fine locally, but I'm a little lost as to how the selector changed.

**Comment by 100stacks** [comment]
@Droogans, ok thanks.  I was wondering what that screenshot represented. 😉

**Comment by Droogans** [comment]
@CITguy I'm closing this and seeing if/when it reappears for the rest of the day today.

**Comment by CITguy** [comment]
👍

**Pull request closed without merging**
