### PR TITLE
Screenshots for rackerlabs/encore-ui#1148

### PR DESCRIPTION
**Pull request by comeatmebro**
See rackerlabs/encore-ui#1148

### CODE REVIEW

**Comment by Droogans** [comment]
I think this should just be the left hand nav only. Not the entire demo app.

**Comment by CITguy** [comment]
This shows the two demo `rxApp` elements within the main `rxApp`. Upcoming CSS changes could potentially change display within the demos, not just the nav.

**Comment by parlarjb** [comment]
Note that the nav for the "Standard page title" screenshots is coming live from the CDN JSON. That means we'll get random visual regression notices after we add new nav items

**Comment by CITguy** [comment]
@parlarjb, good point. What I need to test should be doable with just the custom rxApp implementation, so I'll update the visual regression PR to only include that item.

**Pull request closed without merging**
