### PR TITLE
Screenshots for rackerlabs/encore-ui#1308

### PR DESCRIPTION
**Pull request by comeatmebro**
See rackerlabs/encore-ui#1308

### CODE REVIEW

**Comment by Droogans** [comment]
@CITguy I think this deserves a manual check to see why these look so different. Is it CSS changes? If not, I wouldn't worry about it and merge them as the new baseline as it's probably a change in the way Firefox's selenium driver now handles screenshots.

**Comment by CITguy** [comment]
So these images look much better than the ones we've been seeing lately.

**Comment by CITguy** [comment]
Really, the only ones that look off are the first three (rxApp), and I think they may have something to do with screen resolution.

**Comment by CITguy** [comment]
I'm okay with these screenshots, for sake of continuing visual regression testing.

**Comment by CITguy** [comment]
LGTM

**Pull request merged**
